export enum Role {
  SYSTEM_ADMIN       = 'SYSTEM_ADMIN',
  HOSPITAL_ADMIN     = 'HOSPITAL_ADMIN',
  POLICE_ADMIN       = 'POLICE_ADMIN',
  FIRE_SERVICE_ADMIN = 'FIRE_SERVICE_ADMIN',
  AMBULANCE_DRIVER   = 'AMBULANCE_DRIVER',
}
